version: '3'

services:
  www:
    image: php:apache
    volumes:
     - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=stop_watch
      - MYSQL_USER=fullstack_app
      - MYSQL_PASSWORD=pass 
      - MYSQL_ALLOW-EMPTY_PASSWORD=1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306